import {
  AceOfClubs,
  AceOfDiamonds,
  AceOfHearts,
  AceOfSpades,
  EightOfClubs,
  EightOfDiamonds,
  EightOfHearts,
  EightOfSpades,
  FiveOfClubs,
  FiveOfDiamonds,
  FiveOfHearts,
  FiveOfSpades,
  FourOfClubs,
  FourOfDiamonds,
  FourOfHearts,
  FourOfSpades,
  JackOfClubs,
  JackOfDiamonds,
  JackOfHearts,
  JackOfSpades,
  KingOfClubs,
  KingOfDiamonds,
  KingOfHearts,
  KingOfSpades,
  NineOfClubs,
  NineOfDiamonds,
  NineOfHearts,
  NineOfSpades,
  QueenOfClubs,
  QueenOfDiamonds,
  QueenOfHearts,
  QueenOfSpades,
  SevenOfClubs,
  SevenOfDiamonds,
  SevenOfHearts,
  SevenOfSpades,
  SixOfClubs,
  SixOfDiamonds,
  SixOfHearts,
  SixOfSpades,
  TenOfClubs,
  TenOfDiamonds,
  TenOfHearts,
  TenOfSpades,
  ThreeOfClubs,
  ThreeOfDiamonds,
  ThreeOfHearts,
  ThreeOfSpades,
  TwoOfClubs,
  TwoOfDiamonds,
  TwoOfHearts,
  TwoOfSpades,
} from './card-svgs';

enum CardCode {
  TwoOfClubs = '2C',
  TwoOfDiamonds = '2D',
  TwoOfHearts = '2H',
  TwoOfSpades = '2S',
  ThreeOfClubs = '3C',
  ThreeOfDiamonds = '3D',
  ThreeOfHearts = '3H',
  ThreeOfSpades = '3S',
  FourOfClubs = '4C',
  FourOfDiamonds = '4D',
  FourOfHearts = '4H',
  FourOfSpades = '4S',
  FiveOfClubs = '5C',
  FiveOfDiamonds = '5D',
  FiveOfHearts = '5H',
  FiveOfSpades = '5S',
  SixOfClubs = '6C',
  SixOfDiamonds = '6D',
  SixOfHearts = '6H',
  SixOfSpades = '6S',
  SevenOfClubs = '7C',
  SevenOfDiamonds = '7D',
  SevenOfHearts = '7H',
  SevenOfSpades = '7S',
  EightOfClubs = '8C',
  EightOfDiamonds = '8D',
  EightOfHearts = '8H',
  EightOfSpades = '8S',
  NineOfClubs = '9C',
  NineOfDiamonds = '9D',
  NineOfHearts = '9H',
  NineOfSpades = '9S',
  TenOfClubs = 'TC',
  TenOfDiamonds = 'TD',
  TenOfHearts = 'TH',
  TenOfSpades = 'TS',
  JackOfClubs = 'JC',
  JackOfDiamonds = 'JD',
  JackOfHearts = 'JH',
  JackOfSpades = 'JS',
  QueenOfClubs = 'QC',
  QueenOfDiamonds = 'QD',
  QueenOfHearts = 'QH',
  QueenOfSpades = 'QS',
  KingOfClubs = 'KC',
  KingOfDiamonds = 'KD',
  KingOfHearts = 'KH',
  KingOfSpades = 'KS',
  AceOfClubs = 'AC',
  AceOfDiamonds = 'AD',
  AceOfHearts = 'AH',
  AceOfSpades = 'AS',
}

const cardMap = {
  [CardCode.TwoOfClubs]: TwoOfClubs,
  [CardCode.TwoOfDiamonds]: TwoOfDiamonds,
  [CardCode.TwoOfHearts]: TwoOfHearts,
  [CardCode.TwoOfSpades]: TwoOfSpades,
  [CardCode.ThreeOfClubs]: ThreeOfClubs,
  [CardCode.ThreeOfDiamonds]: ThreeOfDiamonds,
  [CardCode.ThreeOfHearts]: ThreeOfHearts,
  [CardCode.ThreeOfSpades]: ThreeOfSpades,
  [CardCode.FourOfClubs]: FourOfClubs,
  [CardCode.FourOfDiamonds]: FourOfDiamonds,
  [CardCode.FourOfHearts]: FourOfHearts,
  [CardCode.FourOfSpades]: FourOfSpades,
  [CardCode.FiveOfClubs]: FiveOfClubs,
  [CardCode.FiveOfDiamonds]: FiveOfDiamonds,
  [CardCode.FiveOfHearts]: FiveOfHearts,
  [CardCode.FiveOfSpades]: FiveOfSpades,
  [CardCode.SixOfClubs]: SixOfClubs,
  [CardCode.SixOfDiamonds]: SixOfDiamonds,
  [CardCode.SixOfHearts]: SixOfHearts,
  [CardCode.SixOfSpades]: SixOfSpades,
  [CardCode.SevenOfClubs]: SevenOfClubs,
  [CardCode.SevenOfDiamonds]: SevenOfDiamonds,
  [CardCode.SevenOfHearts]: SevenOfHearts,
  [CardCode.SevenOfSpades]: SevenOfSpades,
  [CardCode.EightOfClubs]: EightOfClubs,
  [CardCode.EightOfDiamonds]: EightOfDiamonds,
  [CardCode.EightOfHearts]: EightOfHearts,
  [CardCode.EightOfSpades]: EightOfSpades,
  [CardCode.NineOfClubs]: NineOfClubs,
  [CardCode.NineOfDiamonds]: NineOfDiamonds,
  [CardCode.NineOfHearts]: NineOfHearts,
  [CardCode.NineOfSpades]: NineOfSpades,
  [CardCode.TenOfClubs]: TenOfClubs,
  [CardCode.TenOfDiamonds]: TenOfDiamonds,
  [CardCode.TenOfHearts]: TenOfHearts,
  [CardCode.TenOfSpades]: TenOfSpades,
  [CardCode.JackOfClubs]: JackOfClubs,
  [CardCode.JackOfDiamonds]: JackOfDiamonds,
  [CardCode.JackOfHearts]: JackOfHearts,
  [CardCode.JackOfSpades]: JackOfSpades,
  [CardCode.QueenOfClubs]: QueenOfClubs,
  [CardCode.QueenOfDiamonds]: QueenOfDiamonds,
  [CardCode.QueenOfHearts]: QueenOfHearts,
  [CardCode.QueenOfSpades]: QueenOfSpades,
  [CardCode.KingOfClubs]: KingOfClubs,
  [CardCode.KingOfDiamonds]: KingOfDiamonds,
  [CardCode.KingOfHearts]: KingOfHearts,
  [CardCode.KingOfSpades]: KingOfSpades,
  [CardCode.AceOfClubs]: AceOfClubs,
  [CardCode.AceOfDiamonds]: AceOfDiamonds,
  [CardCode.AceOfHearts]: AceOfHearts,
  [CardCode.AceOfSpades]: AceOfSpades,
};

export { cardMap, CardCode };
