# Usage:
# With the REST Client extension in vscode, the below requests will show an option 
# to send the request as a curl command. 

### !!!! This will error with `not_authed` if you have not used the `signin.http` test-request first

POST http://localhost:3000/api/poker-tables.join
content-type: application/json

{
    "selectedSeatNumber": 1
}

### !!!! This will error with `not_authed` if you have not used the `signin.http` test-request first

POST http://localhost:3000/api/poker-tables.join
content-type: application/json

{
    "selectedSeatNumber": 1234
}