# Usage:
With the REST Client extension in vscode, the below requests will show an option 
to send the request as a curl command. 

###
GET http://localhost:3000/api/actions

###

POST http://localhost:3000/api/actions
content-type: application/json

{
    "test": "Hello world",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:3000/api/tables/tables.create
content-type: application/json

{
    "name": "Hello world",
    "numSeats": 2
}