# Usage:
# With the REST Client extension in vscode, the below requests will show an option 
# to send the request as a curl command. 

### should return method_not_implemented

POST http://localhost:3000/api/actions/signin
content-type: application/json

{
    "username": "richard",
    "password": "abc123"
}

### should error with Invalid request payload and error_details:

POST http://localhost:3000/api/actions/signin
content-type: application/json

{
    "username": "",
    "password": "abc123"
}