# Usage:
# With the REST Client extension in vscode, the below requests will show an option 
# to send the request as a curl command. 

### should sign in

POST http://localhost:3000/api/users.signin
content-type: application/json

{
    "username": "richard",
    "password": "testpassword"
}

### should error with invalid_request_payload and error_details:

POST http://localhost:3000/api/users.signin
content-type: application/json

{
    "username": "",
    "password": "abc123"
}