# Usage:
# With the REST Client extension in vscode, the below requests will show an option 
# to send the request as a curl command. 

POST http://localhost:3000/api/actions/tables.leave
content-type: application/json

{
    "selectedSeatNumber": "seat-1",
    "socketId": "abc123"
}