import { CardCode } from './CardCode';
import {
  AceOfClubs,
  AceOfDiamonds,
  AceOfHearts,
  AceOfSpades,
  EightOfClubs,
  EightOfDiamonds,
  EightOfHearts,
  EightOfSpades,
  FaceDownCard,
  FaceDownCards,
  FiveOfClubs,
  FiveOfDiamonds,
  FiveOfHearts,
  FiveOfSpades,
  FourOfClubs,
  FourOfDiamonds,
  FourOfHearts,
  FourOfSpades,
  JackOfClubs,
  JackOfDiamonds,
  JackOfHearts,
  JackOfSpades,
  KingOfClubs,
  KingOfDiamonds,
  KingOfHearts,
  KingOfSpades,
  NineOfClubs,
  NineOfDiamonds,
  NineOfHearts,
  NineOfSpades,
  QueenOfClubs,
  QueenOfDiamonds,
  QueenOfHearts,
  QueenOfSpades,
  SevenOfClubs,
  SevenOfDiamonds,
  SevenOfHearts,
  SevenOfSpades,
  SixOfClubs,
  SixOfDiamonds,
  SixOfHearts,
  SixOfSpades,
  TenOfClubs,
  TenOfDiamonds,
  TenOfHearts,
  TenOfSpades,
  ThreeOfClubs,
  ThreeOfDiamonds,
  ThreeOfHearts,
  ThreeOfSpades,
  TwoOfClubs,
  TwoOfDiamonds,
  TwoOfHearts,
  TwoOfSpades,
} from './card-svgs';

const cardMap = {
  [CardCode.FaceDownCard]: FaceDownCard,
  [CardCode.FaceDownCards]: FaceDownCards,
  [CardCode.TwoOfClubs]: TwoOfClubs,
  [CardCode.TwoOfDiamonds]: TwoOfDiamonds,
  [CardCode.TwoOfHearts]: TwoOfHearts,
  [CardCode.TwoOfSpades]: TwoOfSpades,
  [CardCode.ThreeOfClubs]: ThreeOfClubs,
  [CardCode.ThreeOfDiamonds]: ThreeOfDiamonds,
  [CardCode.ThreeOfHearts]: ThreeOfHearts,
  [CardCode.ThreeOfSpades]: ThreeOfSpades,
  [CardCode.FourOfClubs]: FourOfClubs,
  [CardCode.FourOfDiamonds]: FourOfDiamonds,
  [CardCode.FourOfHearts]: FourOfHearts,
  [CardCode.FourOfSpades]: FourOfSpades,
  [CardCode.FiveOfClubs]: FiveOfClubs,
  [CardCode.FiveOfDiamonds]: FiveOfDiamonds,
  [CardCode.FiveOfHearts]: FiveOfHearts,
  [CardCode.FiveOfSpades]: FiveOfSpades,
  [CardCode.SixOfClubs]: SixOfClubs,
  [CardCode.SixOfDiamonds]: SixOfDiamonds,
  [CardCode.SixOfHearts]: SixOfHearts,
  [CardCode.SixOfSpades]: SixOfSpades,
  [CardCode.SevenOfClubs]: SevenOfClubs,
  [CardCode.SevenOfDiamonds]: SevenOfDiamonds,
  [CardCode.SevenOfHearts]: SevenOfHearts,
  [CardCode.SevenOfSpades]: SevenOfSpades,
  [CardCode.EightOfClubs]: EightOfClubs,
  [CardCode.EightOfDiamonds]: EightOfDiamonds,
  [CardCode.EightOfHearts]: EightOfHearts,
  [CardCode.EightOfSpades]: EightOfSpades,
  [CardCode.NineOfClubs]: NineOfClubs,
  [CardCode.NineOfDiamonds]: NineOfDiamonds,
  [CardCode.NineOfHearts]: NineOfHearts,
  [CardCode.NineOfSpades]: NineOfSpades,
  [CardCode.TenOfClubs]: TenOfClubs,
  [CardCode.TenOfDiamonds]: TenOfDiamonds,
  [CardCode.TenOfHearts]: TenOfHearts,
  [CardCode.TenOfSpades]: TenOfSpades,
  [CardCode.JackOfClubs]: JackOfClubs,
  [CardCode.JackOfDiamonds]: JackOfDiamonds,
  [CardCode.JackOfHearts]: JackOfHearts,
  [CardCode.JackOfSpades]: JackOfSpades,
  [CardCode.QueenOfClubs]: QueenOfClubs,
  [CardCode.QueenOfDiamonds]: QueenOfDiamonds,
  [CardCode.QueenOfHearts]: QueenOfHearts,
  [CardCode.QueenOfSpades]: QueenOfSpades,
  [CardCode.KingOfClubs]: KingOfClubs,
  [CardCode.KingOfDiamonds]: KingOfDiamonds,
  [CardCode.KingOfHearts]: KingOfHearts,
  [CardCode.KingOfSpades]: KingOfSpades,
  [CardCode.AceOfClubs]: AceOfClubs,
  [CardCode.AceOfDiamonds]: AceOfDiamonds,
  [CardCode.AceOfHearts]: AceOfHearts,
  [CardCode.AceOfSpades]: AceOfSpades,
};

const newMap = {
  ['AS']: AceOfSpades,
};

export { cardMap, newMap };
