import { CardShortCode } from '../../../../backend/src/shared/game/types/CardShortCode';
import {
  AceOfClubs,
  AceOfDiamonds,
  AceOfHearts,
  AceOfSpades,
  EightOfClubs,
  EightOfDiamonds,
  EightOfHearts,
  EightOfSpades,
  FaceDownCard,
  FaceDownCards,
  FiveOfClubs,
  FiveOfDiamonds,
  FiveOfHearts,
  FiveOfSpades,
  FourOfClubs,
  FourOfDiamonds,
  FourOfHearts,
  FourOfSpades,
  JackOfClubs,
  JackOfDiamonds,
  JackOfHearts,
  JackOfSpades,
  KingOfClubs,
  KingOfDiamonds,
  KingOfHearts,
  KingOfSpades,
  NineOfClubs,
  NineOfDiamonds,
  NineOfHearts,
  NineOfSpades,
  QueenOfClubs,
  QueenOfDiamonds,
  QueenOfHearts,
  QueenOfSpades,
  SevenOfClubs,
  SevenOfDiamonds,
  SevenOfHearts,
  SevenOfSpades,
  SixOfClubs,
  SixOfDiamonds,
  SixOfHearts,
  SixOfSpades,
  TenOfClubs,
  TenOfDiamonds,
  TenOfHearts,
  TenOfSpades,
  ThreeOfClubs,
  ThreeOfDiamonds,
  ThreeOfHearts,
  ThreeOfSpades,
  TwoOfClubs,
  TwoOfDiamonds,
  TwoOfHearts,
  TwoOfSpades,
} from './card-svgs';

const cardMap = {
  [CardShortCode.FaceDownCard]: FaceDownCard,
  [CardShortCode.FaceDownCards]: FaceDownCards,
  [CardShortCode.TwoOfClubs]: TwoOfClubs,
  [CardShortCode.TwoOfDiamonds]: TwoOfDiamonds,
  [CardShortCode.TwoOfHearts]: TwoOfHearts,
  [CardShortCode.TwoOfSpades]: TwoOfSpades,
  [CardShortCode.ThreeOfClubs]: ThreeOfClubs,
  [CardShortCode.ThreeOfDiamonds]: ThreeOfDiamonds,
  [CardShortCode.ThreeOfHearts]: ThreeOfHearts,
  [CardShortCode.ThreeOfSpades]: ThreeOfSpades,
  [CardShortCode.FourOfClubs]: FourOfClubs,
  [CardShortCode.FourOfDiamonds]: FourOfDiamonds,
  [CardShortCode.FourOfHearts]: FourOfHearts,
  [CardShortCode.FourOfSpades]: FourOfSpades,
  [CardShortCode.FiveOfClubs]: FiveOfClubs,
  [CardShortCode.FiveOfDiamonds]: FiveOfDiamonds,
  [CardShortCode.FiveOfHearts]: FiveOfHearts,
  [CardShortCode.FiveOfSpades]: FiveOfSpades,
  [CardShortCode.SixOfClubs]: SixOfClubs,
  [CardShortCode.SixOfDiamonds]: SixOfDiamonds,
  [CardShortCode.SixOfHearts]: SixOfHearts,
  [CardShortCode.SixOfSpades]: SixOfSpades,
  [CardShortCode.SevenOfClubs]: SevenOfClubs,
  [CardShortCode.SevenOfDiamonds]: SevenOfDiamonds,
  [CardShortCode.SevenOfHearts]: SevenOfHearts,
  [CardShortCode.SevenOfSpades]: SevenOfSpades,
  [CardShortCode.EightOfClubs]: EightOfClubs,
  [CardShortCode.EightOfDiamonds]: EightOfDiamonds,
  [CardShortCode.EightOfHearts]: EightOfHearts,
  [CardShortCode.EightOfSpades]: EightOfSpades,
  [CardShortCode.NineOfClubs]: NineOfClubs,
  [CardShortCode.NineOfDiamonds]: NineOfDiamonds,
  [CardShortCode.NineOfHearts]: NineOfHearts,
  [CardShortCode.NineOfSpades]: NineOfSpades,
  [CardShortCode.TenOfClubs]: TenOfClubs,
  [CardShortCode.TenOfDiamonds]: TenOfDiamonds,
  [CardShortCode.TenOfHearts]: TenOfHearts,
  [CardShortCode.TenOfSpades]: TenOfSpades,
  [CardShortCode.JackOfClubs]: JackOfClubs,
  [CardShortCode.JackOfDiamonds]: JackOfDiamonds,
  [CardShortCode.JackOfHearts]: JackOfHearts,
  [CardShortCode.JackOfSpades]: JackOfSpades,
  [CardShortCode.QueenOfClubs]: QueenOfClubs,
  [CardShortCode.QueenOfDiamonds]: QueenOfDiamonds,
  [CardShortCode.QueenOfHearts]: QueenOfHearts,
  [CardShortCode.QueenOfSpades]: QueenOfSpades,
  [CardShortCode.KingOfClubs]: KingOfClubs,
  [CardShortCode.KingOfDiamonds]: KingOfDiamonds,
  [CardShortCode.KingOfHearts]: KingOfHearts,
  [CardShortCode.KingOfSpades]: KingOfSpades,
  [CardShortCode.AceOfClubs]: AceOfClubs,
  [CardShortCode.AceOfDiamonds]: AceOfDiamonds,
  [CardShortCode.AceOfHearts]: AceOfHearts,
  [CardShortCode.AceOfSpades]: AceOfSpades,
};

export { cardMap };
